# Generated by Django 2.2.5 on 2019-11-26 13:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=core.models._get_image_uuid4)),
                ('label', models.CharField(choices=[(0, 'Dog'), (1, 'Cat')], max_length=16)),
                ('model', models.CharField(choices=[(0, 'svm'), (1, 'cnn')], max_length=32)),
                ('prediction', models.CharField(choices=[(0, 'Dog'), (1, 'Cat')], max_length=16)),
            ],
        ),
    ]
