# Generated by Django 2.2.5 on 2019-11-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='label',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='model',
            field=models.CharField(choices=[('svm', 'svm'), ('cnn', 'cnn')], max_length=32),
        ),
        migrations.AlterField(
            model_name='history',
            name='prediction',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=16),
        ),
    ]
