# Generated by Django 2.2.5 on 2019-11-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191127_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='label',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='model',
            field=models.CharField(choices=[('svm', 'SVM'), ('cnn', 'CNN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='history',
            name='prediction',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=16),
        ),
    ]
